### ISSUE TITLE
Add CI with Travis

### ISSUE THREAD

**Issue by NewLunarFire** [NewLunarFire/pointsgenie#1]
We have all the tooling set up (build, tests, etc.) for the website. What I would like to have is some automatic CI with Travis.

Optionally, add a badge in the README and prevent PRs from being merged if CI fails.

**Comment by greybutton** [comment]
I'll help you

**Comment by greybutton** [comment]
You may "sign in with GitHub" https://travis-ci.org/, then in your profile you can add repositories.
To add a badge in the README you need after build click on badge in travis, pick "Markdown", copy code and paste into README.md. 
You can prevent PRs in travis repository settings.

**Comment by NewLunarFire** [comment]
Thanks, this is enabled: https://travis-ci.org/NewLunarFire/pointsgenie
What I would need is a .travis.yml file to do a simple dry-run and run the tests. The readme says node 0.11 but it should work under node 8.

**Comment by greybutton** [comment]
I did update node to 8.
You can check build here: https://travis-ci.org/greybutton/pointsgenie#L436
This article can be helpful for you https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by NewLunarFire** [comment]
I thought it would be more complicated but it looks fine, thanks 😄 . Tests are failing because I renamed an endpoint for legal reasons and haven't fixed the tests yet, I'll have to get to it soon.
